### ISSUE TITLE
Feature: Facebook Importer

### ISSUE THREAD

**Issue by genisplaja** [totetmatt/gephi-plugins#11]
## Expected Behavior
Create a new feature to import a graph based on your Facebook friends or posts
## Current Behavior
Not implemented
## Possible Solution
We want to try to do a feature similar to the twitter importer but using Facebook API

## Context
As this feature is only implemented for twitter, we would like extend it to other social networks, in our case facebook.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: Java 12.0.1
* Operating System: Windows

**Comment by totetmatt** [comment]
Hello,

Unfortunatelly, this feature can't be implemented for the moment.

The plugin is focused on *Twitter*, which is quite different platform from Facebook, and focused on *Streaming*, which is a concept that doesn't really exists in the Facebook platform. It would require at minimum a complete refactoring / forking of the entire current plugin to match Facebook use cases and a reflexion about common network projection applied to Facebook platform that would be used by most of the public. 
Moreover, Facebook API, for "default application access", isn't as open as Twitter Api in terms of data retrivial, which drastically limit and reduce the quality of data available to generate graph. 
Finally, data acquision on Facebook has been considerably controlled and regulated by Facebook policies and by the European GDPR act, preventing almost any import of personal data from Facebook platform.
