### ISSUE TITLE
Idea/Request: Get GeoTagging of tweets

### ISSUE THREAD

**Issue by DavidGigli** [totetmatt/gephi-plugins#3]
I've no idea how this could be difficoult, but would be nice to have the geotag of tweets, so that they also could be mapped on world/city maps, what do you think?

**Comment by totetmatt** [comment]
Do you think about more information of the tweet when using the "Full Twitter" Networklogic or a complete new Networklogic that just display tweets which has Geo localisation information ?

**Comment by DavidGigli** [comment]
I was thinking about more information of the tweet, a new column in the data laboratory with the geo tag info for the tweets that have those info.

Il 29 aprile 2016 13:05:37 CEST, Totet notifications@github.com ha scritto:

> Do you think about more information of the tweet when using the "Full
> Twitter" Networklogic or a complete new Networklogic that just display
> tweets which has Geo localisation information ?
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/totetmatt/gephi-plugins/issues/3#issuecomment-215685105

## 

Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by totetmatt** [comment]
Geo data and Place are now part of tweet attributes (v1.1.1)
