### ISSUE TITLE
Twitter Streaming Importer v1.1.1 Not Connecting

### ISSUE THREAD

**Issue by mechmillan** [totetmatt/gephi-plugins#7]
Hi, 

Thank you for your work on this plugin, it seems like it will be really helpful for quick, cursory twitter tag analysis.

I was following along to the plugin tutorial [Streaming Importer](https://github.com/seinecle/gephi-tutorials/blob/master/src/main/asciidoc/en/plugins/twitter-streaming-importer-en.adoc) and after adding my API Key, API Secret, Access Token and Access Token Secret, I tried to apply the Network Logic option(s) but the plugin seems to hang when clicking 'Connect'. No Nodes or Edges are loading and I have tried both 'Words to follow' and 'Users to follow', with multiple queries and the 3 different types of Network Logic options. 

Below is info on my current version of Gephi, and all plugins are up to date:
Product Version: Gephi 0.9.1 201510222201
Java: 1.8.0_131; Java HotSpot(TM) Client VM 25.131-b11
Runtime: Java(TM) SE Runtime Environment 1.8.0_131-b11
System: Windows 10 version 10.0 running on x86; Cp1252; en_US (gephi)

Version of TwitterStreamingImporter: Version: 1.1.1

I have regenerated my keys and tokens multiple times as well as activated/deactivated the plugin (and uninstalled/reinstalled) with no success. Is there any alternate troubleshooting tips that I should be trying?

**Comment by totetmatt** [comment]
Hi ! 
Can you describe 'hang when clicking connect' ? Does it change to disconect ? Does the connect button looks 'clickable' or gray 'disabled' ?

**Comment by mechmillan** [comment]
Hi, 

Sorry, I should have been a little more clear - I can click 'Connect' and it changes to 'Disconnect' (highlighted blue with grey border) but no nodes/edges seem to be loading, even after several minutes.

**Comment by totetmatt** [comment]
Ok no worries.

Then I suppose you tested with some popular words. 
Can you start gephi within a terminal and tell me the output when you try to connect ?

**Comment by mechmillan** [comment]
Sure thing, the following is the output: 

PS C:\Users\Alfonso> start "C:\Program Files (x86)\Gephi-0.9.1\bin\gephi64
PS C:\Users\Alfonso>
The launcher has determined that the parent process has a console and will reuse it for its own console output. Closing the console will result in termination of the running program.
Use '--console suppress' to suppress console output.
Use '--console new' to create a separate console window. 
[Tue Jun 27 10:23:39 PDT 2017] Establishing connection.
[Tue Jun 27 10:24:10 PDT 2017] Connection established.
[Tue Jun 27 10:24:10 PDT 2017] Receiving status stream.

I used the 'Words to follow' of 'madewithgephi' and there has been no change to the terminal output in about 4 minutes.

**Comment by totetmatt** [comment]
Hum actually it looks ok. Try with a more common word (like 'apple')

**Comment by mechmillan** [comment]
Ah, yes it definitely works with more common words (tried 'apple' and 'NBAAwards') and the nodes/edges populated immediately - for less popular words, should I be leaving the stream on for quite a while? Thank you for your help with this.

**Comment by totetmatt** [comment]
Yeah so to explain and for the records .

The Stream plugin is using the Stream API of twitter, which just send "Real time" tweets on going on twitter. It doesn't use the standard API to retrive existing tweets.

So yes, for less popular words, you need to let it live longer before having result. But actually it was build to visualize "hot" topic ;-)

Have fun
